language: python
os:
  - linux
  #- windows
  # - osx
python :
  - "3.9"
  #- "nightly"

install:
  # could try
  # - conda install mamba=1.2.0 -c conda-forge -y
  # the use micromamba instead, which should be faster

  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

  # Use the YML file instead of the command line below
  - conda env create -q -f py3-opgee-travis.yml

  - conda activate opgee
  - python -m pip install .

  - pip install pytest-cov codecov coveralls PyYAML

addons:
  apt:
    packages:
      - graphviz

script:
  - coverage run --source=opgee -m pytest

env:
  # set OPGEE_HOME so the test opgee.cfg file is found
  OPGEE_HOME=/home/travis/build/Stanford-EAO/OPGEEv4/tests/files

notifications:
  email: true

branches:
  only:
  - master
  - test-travis
  - /v(\d+)\.(\d+)\.*/

matrix:
  allow_failures:
  - python: nightly

codecov: true

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
